# Generated by Django 4.0.4 on 2022-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_addition_functionrate_alter_eventworker_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventworker',
            name='additions',
            field=models.ManyToManyField(to='payroll.addition'),
        ),
    ]
