import { IRow } from "../../components/elements/Table/TableBody";

export const header = [
  "Event",
  "Start",
  "End",
  "Work Time",
  "Rate",
  "Overtime Rate",
  "Additions",
  "Total",
];
const dateNow = () => {
  const d = new Date(Date.now());
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(d);
};
export const fakeData = [
  {
    id: 1,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 2,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 3,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 4,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 5,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 6,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 7,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 8,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 9,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 10,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 11,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 12,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 13,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 14,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 15,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 16,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 17,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 18,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 19,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 20,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 21,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 22,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
  {
    id: 23,
    event: "22-201-PolandRock",
    start: dateNow(),
    end: dateNow(),
    work_time: 12,
    rate: 550,
    overtime_rate: 110,
    additions: {},
    total: 660,
  },
];
export const prepareDataToTable = (data: Array<any>) => {
  const result = [];
  for (const day of data) {
    const dayResult: IRow = {
      id: day.id,
      cells: [
        `${day.event.number}-${day.event.name}`,
        day.start.toString(),
        day.end.toString(),
        day.work_time.toString(),
        day.rate.toString(),
        day.overtime_rate.toString(),
        day.additions.toString(),
        day.total.toString(),
      ],
    };
    result.push(dayResult);
  }
  return result;
};
